mod_key = "mod4"
browser = "firefox"
file_manager = "vifm"

autostart_applications = [
    # xset commands disable screen saver
    "xset -dpms &",
    "xset -q &",
    # picom enables transparent tiles
    "picom -b --experimental-backends",
    # nitrogen for backgrounds
    "nitrogen --restore &",
]

[terminal]
run = "alacritty"
run_command = "alacritty -e"
hold_command = "alacritty --hold -e"

# Yaru colors
[palette]
blue_0 = "#75d3f4"
blue_2 = "#47c4f1"
blue_3 = "#19B6EE" # Yaru blue
blue_4 = "#007aa6" # Yaru linkblue
blue_5 = "#335280" # Yaru darkblue
green_1 = "#5AED70"
green_2 = "#47D35C"
green_3 = "#34B948"
green_4 = "#219E34"
green_5 = "#0e8420" # Yaru green
yellow_1 = "#FCCD87"
yellow_2 = "#FBC16A"
yellow_3 = "#FBB44C"
yellow_4 = "#FAA82F"
yellow_5 = "#F99B11" # Yaru yellow
orange_1 = "#F29879"
orange_2 = "#F08763"
orange_3 = "#ED764D"
orange_4 = "#EB6536"
orange_5 = "#E95420" # Yaru orange
red_1 = "#EA485C"
red_2 = "#DE374C"
red_3 = "#D3273B"
red_4 = "#c7162b" # Yaru red
red_5 = "#a91224"
purple_1 = "#924D8B" # Yaru aubergine
purple_2 = "#762572" # Yaru purple
purple_3 = "#77216F" # Yaru light aubergine
purple_4 = "#5E2750" # Yaru mid aubergine
purple_5 = "#2C001E" # Yaru dark aubergine
brown_1 = "#E1B289"
brown_2 = "#C5976E"
brown_3 = "#AA7B53"
brown_4 = "#8E6038"
brown_5 = "#72441D"
light_1 = "#FFFFFF"
light_2 = "#F7F7F7" # Yaru porcelain
light_3 = "#CCC" # Yaru silk
light_4 = "#AEA79F" # Yaru warm gray
light_5 = "#878787" # Yaru ash
dark_1 = "#666666" # Yaru graphite
dark_2 = "#5D5D5D" # Yaru slate
dark_3 = "#3D3D3D" # Yaru inkstone
dark_4 = "#181818" # Yaru jet
dark_5 = "#000000"

